test: &default

  # Credentials for REST APIs
  client_id: AQ37AUmyTsiUDWpJwneUkl8Aj6GcIJc_IMgK48henDoXrfLMmOUZEp-zskKot7OMzm5TY4xh17bz-aRL
  client_secret: EBVgfNsxLKqg3IU5r0dzpTXWU9ss0lKT34LdtyC8k3St1k8iBj9J2m4TTcCBWTHSCYabT3yque1GtS1W

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: kyle.buzby-facilitator_api1.gmail.com
  password: 77WQAPC37HNAU5FL
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7z5lF.yfeSxWtamP7VPKvH9f4bQ
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: kyle.buzby-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  mode: live
